services:
    appventus_almanach_kernelrequest_listener:
        class: AppVentus\AlmanachBundle\Listener\KernelRequestListener
        arguments:
            - @twig
            - %almanach%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    appventus_almanach_display:
        class: AppVentus\AlmanachBundle\Twig\AlmanachDisplayExtension
        arguments:
            - %almanach%
            - @twig
            - %almanach.framework%
        tags:
            - { name: twig.extension }
